# Generated by Django 4.2.10 on 2024-03-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person_info',
            table='personal_info',
        ),
    ]
